### ISSUE TITLE
Where is your 【yolov7-w6-pose-nms.onnx】？

### ISSUE THREAD

**Issue by Eomerdon** [trancongman276/yolov7-pose#1]
Hi, guys, I have read your 【README.md】, but it's really disappointed that I can't download the [yolov7-w6-pose-nms.onnx](https://drive.google.com/file/d/1Fbl7p6CtdEUyLgVHjUCBU3auX-EV9COg/view?usp=sharing).

so, where is it? Can you give it to me? Thank you very much.

And I also saw 【./weights/yolov7-w6-pose-nms.onnx】in your code 【run.py】
but I didn't see 【./weights】 path in your master branch.

**Comment by trancongman276** [comment]
Hi, sorry for the late reply.
I've just checked the link above, it's apparently still available for me. Please check again.
The `./weights/yolov7-w6-pose-nms.onnx` is the path you save the weight. You can change it directly or add it as an arguments when you run the script: `python run.py --input_path input.jpg --output_path results --model_path <your_weight_path>`.
Thank you.

**Comment by Eomerdon** [comment]
Later, I have successfully downloaded your [yolov7-w6-pose-nms.onnx](https://drive.google.com/file/d/1Fbl7p6CtdEUyLgVHjUCBU3auX-EV9COg/view?usp=sharing).
Thank you for the reply.
@trancongman276
