### ISSUE TITLE
Conversion of yolov7 pose torch model to onnx

### ISSUE THREAD

**Issue by maketo97** [trancongman276/yolov7-pose#2]
@trancongman276 May I know how do you convert the yolov7 pose torch model to onnx model with --export-nms=True? Thanks

**Comment by trancongman276** [comment]
> @trancongman276 May I know how do you convert the yolov7 pose torch model to onnx model with --export-nms=True? Thanks

Hi! I will upload this part in the future. Thank you <3

**Comment by maketo97** [comment]
Ok, looking forward to your update in the near future 😁

**Comment by yellowjs0304** [comment]
How can i convert pt to onnx??? @trancongman276

**Comment by trancongman276** [comment]
https://github.com/trancongman276/yolov7-pose/issues/3#issuecomment-2295065758
