### ISSUE TITLE
How to convert pt to your onnx

### ISSUE THREAD

**Issue by lxiaoxiaoxing** [trancongman276/yolov7-pose#3]
Hi, How to convert yolov7-w6-pose.pt to your onnx.Could anyone give me an answer?

**Comment by ZhangLe-fighting** [comment]
+1

**Comment by andorxornot** [comment]
+1

**Comment by zcunyi** [comment]
+1

**Comment by IamSVP94** [comment]
+1

**Comment by nguyenthuy1681999** [comment]
+1

**Comment by trancongman276** [comment]
Hi, sorry for the long wait, I've uploaded the convert code
https://github.com/trancongman276/yolov7-pose/blob/master/ConvertYOLOv7PoseONNX.ipynb
Cheers.
